use super::parsing::prelude::*;
use super::prelude::*;


#[derive(Debug)]
pub struct Skipped;

impl<T: BufRead> ParseSection<T> for Skipped {
    fn parse(reader: &mut Reader<T>, _event: &BytesStart) -> Result<Self, Error> {
        skip_section(reader)?;
        Ok(Skipped)
    }
}

pub fn skip_section<T: BufRead>(reader: &mut Reader<T>) -> Result<(), Error> {
    let mut buf = Vec::new();
    let mut depth = 0;
    loop {
        match reader.read_event_into(&mut buf)? {
            Event::Start(e) if start_eq(&e, "subSection") => depth += 1,
            Event::Start(e) if start_eq(&e, "subSubSection") => depth += 1,
            Event::End(e) if end_eq(&e, "subSubSection") || end_eq(&e, "subSection") => {
                // also skip nested subsections
                // example: EFB5B55CDA31F8FB1F839CC060557790.xml
                if depth <= 0 {
                    break;
                }
                else {
                    depth -= 1;
                }
            }
            _ => {}
        }
    }
    Ok(())
}


#[derive(Debug)]
pub enum Section {
    Nomenclature(Nomenclature),
    Description(Skipped),
    OriginalDescription(Skipped),
    ReferenceGroup(Skipped),
    MaterialsExamined(Skipped),
    SpecimensExamined(Skipped),
    BiologyEcology(Skipped),
    Biology(Skipped),
    Discussion(Skipped),
    Occurrences(Skipped),
    TypeSpecimens(Skipped),
    Diagnosis(Skipped),
    Etymology(Skipped),
    Distribution(Skipped),
    Notes(Skipped),
    Remarks(Skipped),
    Multiple(Skipped), // what is?
    TypeTaxon(Skipped),
    TypeHost(Skipped),
    InfectionSite(Skipped),
    TypeLocality(Skipped),
    Paratype(Skipped),
    References(Skipped),
    OriginalSource(Skipped),
    TypeHorizon(Skipped),
    VernacularNames(Skipped),
    Conservation(Skipped),
    TypeSpecies(Skipped),
    FamilyPlacement(Skipped),
    Holotype(Skipped),
    Hosts(Skipped),
    MolecularData(Skipped),
    Records(Skipped),
    EcologicalInteractions(Skipped),
    Types(Skipped),
    Ecology(Skipped),
    ConservationStatus(Skipped),
    Key(Skipped),
    DiagnosticCharacters(Skipped),
    Redescription(Skipped),
    ParasiteOf(Skipped),
    Chorology(Skipped),
    BiogeographicalCharacterization(Skipped),
    Habitat(Skipped),
    TypeMaterial(Skipped),
    FeedsOn(Skipped),
    Comments(Skipped),
    DistributionMapLink(Skipped),
    LectotypeSpecies(Skipped),
    Diagnostics(Skipped),
    EmendedDiagnosis(Skipped),
    Variation(Skipped),
    Call(Skipped),
    Names(Skipped),
    Range(Skipped),
    Uses(Skipped),
    Bionomics(Skipped),
    HolotypeRedescription(Skipped),
    Color(Skipped),
    Morphology(Skipped),
    NewRecords(Skipped),
    SimilarSpecies(Skipped),
    SynonymicList(Skipped),
    SpeciesChecklist(Skipped),
    CurrentStatus(Skipped),
    TypeDeposit(Skipped),
    Label(Skipped),
    Dimensions(Skipped),
    CurrentSystematicPosition(Skipped),
    ComparativeDiagnosis(Skipped),
    OriginalCombination(Skipped),
    CurrentCombination(Skipped),
    CollectionHabitat(Skipped),
    Diversity(Skipped),
    Colouration(Skipped),
    ColourationInLife(Skipped),
    ColourationInAlcohol(Skipped),
    ColourationInPreservative(Skipped),
    TimeOfActivity(Skipped),
    PublishedRecords(Skipped),
    Taxonomy(Skipped),
    Variability(Skipped),
    Affinities(Skipped),
    Chemistry(Skipped),
    NameDerivation(Skipped),
    Locality(Skipped),
    Method(Skipped),
    Eggs(Skipped),
    Collection(Skipped),
    PhotographicEvidence(Skipped),
    NaturalHistory(Skipped),
    Phenology(Skipped),
    DistinguishingFeatures(Skipped),
    Identification(Skipped),
    Associations(Skipped),
    TaxonomicAccount(Skipped),
    TypeGenus(Skipped),
    TaxonomicHistory(Skipped),
    MisappliedName(Skipped),
    HybridizationEvidence(Skipped),
    Gender(Skipped),
    PhylogeneticRelationships(Skipped),
    LocusTypicus(Skipped),
    Colour(Skipped),
    Translation(Skipped),
    NativeStatus(Skipped),
    Size(Skipped),
    Adult(Skipped),
    LarvaPupa(Skipped),
    LarvalMine(Skipped),
    Fitch(Skipped),
    CurrentSeniorSynonym(Skipped),
    Syntypes(Skipped),
    Measurements(Skipped),
    Male(Skipped),
    SelectedLiterature(Skipped),
    AdultMorphology(Skipped),
    Phylogeny(Skipped),
    GeneticData(Skipped),
    Pollen(Skipped),
    SpeciesExamined(Skipped),
    LiteratureRecords(Skipped),
    TemporalData(Skipped),
    SpecificEpithet(Skipped),
    Material(Skipped),
    Depth(Skipped),
    SamplingSites(Skipped),
    RecordsExamined(Skipped),
    Recognition(Skipped),
    IncludedSpecies(Skipped),
    Relationships(Skipped),
    CollectingMethod(Skipped),
    OriginalLocalities(Skipped),
    LifeHistory(Skipped),
    SpecimensSeen(Skipped),
    Bioacoustics(Skipped),
    Illustration(Skipped),
    Comparisons(Skipped),
    Composition(Skipped),
    ChromosomeNumber(Skipped),
    Basionym(Skipped),
    Lectotype(Skipped),
    Referens(Skipped),
    Features(Skipped),
    OtherMaterial(Skipped),
    Literature(Skipped),
    Localities(Skipped),
    Unknown(Skipped),
    Nesting(Skipped),
    Prey(Skipped),
    FoodPlants(Skipped),
    Paratopotype(Skipped),
    GenericPlacement(Skipped),
    Registration(Skipped),
    TypeMaterials(Skipped),
    Substratum(Skipped),
    TypesExamined(Skipped),
    Anatomy(Skipped),
    Similar(Skipped),
    GallerySystem(Skipped),
    CasteDifference(Skipped),
    Chresonymy(Skipped),
    Vocalization(Skipped),
    Synonyms(Skipped),
    Species(Skipped),
    HostPlants(Skipped),
    Caves(Skipped),
    SpecimensDeposited(Skipped),
    OtherHosts(Skipped),
    AdvertisementCall(Skipped),
    MalarSulcus(Skipped),
    PrespecularSulcus(Skipped),
    TransepisternalLine(Skipped),
    ParacoxalSulcus(Skipped),
    MetanotalTrough(Skipped),
    Metascutellum(Skipped),
    WingVenation(Skipped),
    MetasomalFoveae(Skipped),
    MetasomalSegments(Skipped),
    LengthOfMetasomalSegments(Skipped),
    ReferredSpecimens(Skipped),
    Typification(Skipped),
    SpeciesDelimitation(Skipped),
    Head(Skipped),
    Mesosoma(Skipped),
    Metasoma(Skipped),
    Skipped(Skipped),
}


#[derive(Debug)]
pub struct SubSection {
    pub section: Section,
}

impl<T: BufRead> ParseSection<T> for SubSection {
    fn parse(reader: &mut Reader<T>, e: &BytesStart) -> Result<Self, Error> {
        // sometimes a section doesn't have a type so we treat it as an unknown section
        // and just skip it
        // example: 815D710FFFA1FFF0A5A63306FB58F8C2.xml
        let section_type = match parse_attribute_opt(reader, e, "type")? {
            Some(section) => section,
            None => "".to_string(),
        };

        // let section_type = parse_attribute(&reader, &e, "type")?;
        let section = match section_type.as_str() {
            "nomenclature" => Section::Nomenclature(Nomenclature::parse(reader, e)?),
            "description" => Section::Description(Skipped::parse(reader, e)?),
            "reference_group" => Section::ReferenceGroup(Skipped::parse(reader, e)?),
            "materials_examined" => Section::MaterialsExamined(Skipped::parse(reader, e)?),
            "material examined" => Section::MaterialsExamined(Skipped::parse(reader, e)?),
            "specimen examined" => Section::SpecimensExamined(Skipped::parse(reader, e)?),
            "specimens examined" => Section::SpecimensExamined(Skipped::parse(reader, e)?),
            "other specimen examined" => Section::SpecimensExamined(Skipped::parse(reader, e)?),
            "biology_ecology" => Section::BiologyEcology(Skipped::parse(reader, e)?),
            "biology/ecology" => Section::BiologyEcology(Skipped::parse(reader, e)?),
            "biology" => Section::Biology(Skipped::parse(reader, e)?),
            "discussion" => Section::Discussion(Skipped::parse(reader, e)?),
            "occurrence" => Section::Occurrences(Skipped::parse(reader, e)?),
            "occurrence data" => Section::Occurrences(Skipped::parse(reader, e)?),
            "type specimens" => Section::TypeSpecimens(Skipped::parse(reader, e)?),
            "type specimen" => Section::TypeSpecimens(Skipped::parse(reader, e)?),
            "diagnosis" => Section::Diagnosis(Skipped::parse(reader, e)?),
            "etymology" => Section::Etymology(Skipped::parse(reader, e)?),
            "distribution" => Section::Distribution(Skipped::parse(reader, e)?),
            "notes" => Section::Notes(Skipped::parse(reader, e)?),
            "note" => Section::Notes(Skipped::parse(reader, e)?),
            "remarks" => Section::Remarks(Skipped::parse(reader, e)?),
            "multiple" => Section::Multiple(Skipped::parse(reader, e)?),
            "type_taxon" => Section::TypeTaxon(Skipped::parse(reader, e)?),
            "type host" => Section::TypeHost(Skipped::parse(reader, e)?),
            "infection site" => Section::InfectionSite(Skipped::parse(reader, e)?),
            "type locality" => Section::TypeLocality(Skipped::parse(reader, e)?),
            "paratype" => Section::Paratype(Skipped::parse(reader, e)?),
            "paratypes" => Section::Paratype(Skipped::parse(reader, e)?),
            "reference" => Section::References(Skipped::parse(reader, e)?),
            "references" => Section::References(Skipped::parse(reader, e)?),
            "original source" => Section::OriginalSource(Skipped::parse(reader, e)?),
            "type horizon" => Section::TypeHorizon(Skipped::parse(reader, e)?),
            "vernacular_names" => Section::VernacularNames(Skipped::parse(reader, e)?),
            "vernacular name" => Section::VernacularNames(Skipped::parse(reader, e)?),
            "conservation" => Section::Conservation(Skipped::parse(reader, e)?),
            "type species" => Section::TypeSpecies(Skipped::parse(reader, e)?),
            "family placement" => Section::FamilyPlacement(Skipped::parse(reader, e)?),
            "holotype" => Section::Holotype(Skipped::parse(reader, e)?),
            "holotype ♀" => Section::Holotype(Skipped::parse(reader, e)?),
            "holotype ♂" => Section::Holotype(Skipped::parse(reader, e)?),
            "host" => Section::Hosts(Skipped::parse(reader, e)?),
            "hosts" => Section::Hosts(Skipped::parse(reader, e)?),
            "molecular data" => Section::MolecularData(Skipped::parse(reader, e)?),
            "records" => Section::Records(Skipped::parse(reader, e)?),
            "ecological interactions" => Section::EcologicalInteractions(Skipped::parse(reader, e)?),
            "type" => Section::Types(Skipped::parse(reader, e)?),
            "types" => Section::Types(Skipped::parse(reader, e)?),
            "ecology" => Section::Ecology(Skipped::parse(reader, e)?),
            "conservation status" => Section::ConservationStatus(Skipped::parse(reader, e)?),
            "key" => Section::Key(Skipped::parse(reader, e)?),
            "diagnostic characters" => Section::DiagnosticCharacters(Skipped::parse(reader, e)?),
            "redescription" => Section::Redescription(Skipped::parse(reader, e)?),
            "parasite of" => Section::ParasiteOf(Skipped::parse(reader, e)?),
            "chorology" => Section::Chorology(Skipped::parse(reader, e)?),
            "biogeographical characterization" => Section::BiogeographicalCharacterization(Skipped::parse(reader, e)?),
            "habitat" => Section::Habitat(Skipped::parse(reader, e)?),
            "type material" => Section::TypeMaterial(Skipped::parse(reader, e)?),
            "feeds on" => Section::FeedsOn(Skipped::parse(reader, e)?),
            "comments" => Section::Comments(Skipped::parse(reader, e)?),
            "link to distribution map" => Section::DistributionMapLink(Skipped::parse(reader, e)?),
            "lectotype species" => Section::LectotypeSpecies(Skipped::parse(reader, e)?),
            "diagnostics" => Section::Diagnostics(Skipped::parse(reader, e)?),
            "diagnostic features" => Section::Diagnostics(Skipped::parse(reader, e)?),
            "emended diagnosis" => Section::EmendedDiagnosis(Skipped::parse(reader, e)?),
            "variation" => Section::Variation(Skipped::parse(reader, e)?),
            "call" => Section::Call(Skipped::parse(reader, e)?),
            "name" => Section::Names(Skipped::parse(reader, e)?),
            "range" => Section::Range(Skipped::parse(reader, e)?),
            "uses" => Section::Uses(Skipped::parse(reader, e)?),
            "bionomics" => Section::Bionomics(Skipped::parse(reader, e)?),
            "redescription based on holotype" => Section::HolotypeRedescription(Skipped::parse(reader, e)?),
            "color" => Section::Color(Skipped::parse(reader, e)?),
            "morphology" => Section::Morphology(Skipped::parse(reader, e)?),
            "new records" => Section::NewRecords(Skipped::parse(reader, e)?),
            "similar species" => Section::SimilarSpecies(Skipped::parse(reader, e)?),
            "synonymic_list" => Section::SynonymicList(Skipped::parse(reader, e)?),
            "current status" => Section::CurrentStatus(Skipped::parse(reader, e)?),
            "type deposit" => Section::TypeDeposit(Skipped::parse(reader, e)?),
            "label" => Section::Label(Skipped::parse(reader, e)?),
            "dimensions" => Section::Dimensions(Skipped::parse(reader, e)?),
            "current systematic position" => Section::CurrentSystematicPosition(Skipped::parse(reader, e)?),
            "comparative diagnosis" => Section::ComparativeDiagnosis(Skipped::parse(reader, e)?),
            "original combination" => Section::OriginalCombination(Skipped::parse(reader, e)?),
            "current combination" => Section::CurrentCombination(Skipped::parse(reader, e)?),
            "collection and habitat data" => Section::CollectionHabitat(Skipped::parse(reader, e)?),
            "diversity" => Section::Diversity(Skipped::parse(reader, e)?),
            "colouration in life" => Section::ColourationInLife(Skipped::parse(reader, e)?),
            "colouration in alcohol" => Section::ColourationInAlcohol(Skipped::parse(reader, e)?),
            "colour in life" => Section::ColourationInLife(Skipped::parse(reader, e)?),
            "colour in preservative" => Section::ColourationInPreservative(Skipped::parse(reader, e)?),
            "time of activity" => Section::TimeOfActivity(Skipped::parse(reader, e)?),
            "published records" => Section::PublishedRecords(Skipped::parse(reader, e)?),
            "taxonomy" => Section::Taxonomy(Skipped::parse(reader, e)?),
            "variability" => Section::Variability(Skipped::parse(reader, e)?),
            "affinities" => Section::Affinities(Skipped::parse(reader, e)?),
            "affinity" => Section::Affinities(Skipped::parse(reader, e)?),
            "chemistry" => Section::Chemistry(Skipped::parse(reader, e)?),
            "name derivation" => Section::NameDerivation(Skipped::parse(reader, e)?),
            "preliminary conservation status" => Section::ConservationStatus(Skipped::parse(reader, e)?),
            "locality" => Section::Locality(Skipped::parse(reader, e)?),
            "method" => Section::Method(Skipped::parse(reader, e)?),
            "collection" => Section::Collection(Skipped::parse(reader, e)?),
            "photographic evidence" => Section::PhotographicEvidence(Skipped::parse(reader, e)?),
            "natural history" => Section::NaturalHistory(Skipped::parse(reader, e)?),
            "phenology" => Section::Phenology(Skipped::parse(reader, e)?),
            "distinguishing features" => Section::DistinguishingFeatures(Skipped::parse(reader, e)?),
            "identification" => Section::Identification(Skipped::parse(reader, e)?),
            "associations" => Section::Associations(Skipped::parse(reader, e)?),
            "taxonomic account" => Section::TaxonomicAccount(Skipped::parse(reader, e)?),
            "type genus" => Section::TypeGenus(Skipped::parse(reader, e)?),
            "taxonomic history" => Section::TaxonomicHistory(Skipped::parse(reader, e)?),
            "misapplied name" => Section::MisappliedName(Skipped::parse(reader, e)?),
            "evidence of hybridization" => Section::HybridizationEvidence(Skipped::parse(reader, e)?),
            "gender" => Section::Gender(Skipped::parse(reader, e)?),
            "female" => Section::Gender(Skipped::parse(reader, e)?),
            "phylogenetic relationships" => Section::PhylogeneticRelationships(Skipped::parse(reader, e)?),
            "described species" => Section::Description(Skipped::parse(reader, e)?),
            "locus typicus" => Section::LocusTypicus(Skipped::parse(reader, e)?),
            "differential diagnosis" => Section::Diagnosis(Skipped::parse(reader, e)?),
            "colour" => Section::Colour(Skipped::parse(reader, e)?),
            "translation" => Section::Translation(Skipped::parse(reader, e)?),
            "habit and habitat" => Section::Habitat(Skipped::parse(reader, e)?),
            "vernacular" => Section::VernacularNames(Skipped::parse(reader, e)?),
            "native status" => Section::NativeStatus(Skipped::parse(reader, e)?),
            "lineage diagnosis" => Section::Diagnosis(Skipped::parse(reader, e)?),
            "size" => Section::Size(Skipped::parse(reader, e)?),
            "adult" => Section::Adult(Skipped::parse(reader, e)?),
            "larva and pupa" => Section::LarvaPupa(Skipped::parse(reader, e)?),
            "larval mine" => Section::LarvalMine(Skipped::parse(reader, e)?),
            "original description of" => Section::OriginalDescription(Skipped::parse(reader, e)?),
            "fitch" => Section::Fitch(Skipped::parse(reader, e)?),
            "current senior synonym" => Section::CurrentSeniorSynonym(Skipped::parse(reader, e)?),
            "syntypes" => Section::Syntypes(Skipped::parse(reader, e)?),
            "measurements" => Section::Measurements(Skipped::parse(reader, e)?),
            "selected literature" => Section::SelectedLiterature(Skipped::parse(reader, e)?),
            "described species and range" => Section::Description(Skipped::parse(reader, e)?),
            "adult morphology" => Section::AdultMorphology(Skipped::parse(reader, e)?),
            "life history notes" => Section::Notes(Skipped::parse(reader, e)?),
            "taxonomical notes" => Section::Notes(Skipped::parse(reader, e)?),
            "type data" => Section::Types(Skipped::parse(reader, e)?),
            "type material examined" => Section::MaterialsExamined(Skipped::parse(reader, e)?),
            "phylogeny and classification" => Section::Phylogeny(Skipped::parse(reader, e)?),
            "common names" => Section::VernacularNames(Skipped::parse(reader, e)?),
            "preliminary conservation assessment" => Section::Conservation(Skipped::parse(reader, e)?),
            "genetic data" => Section::GeneticData(Skipped::parse(reader, e)?),
            "pollen" => Section::Pollen(Skipped::parse(reader, e)?),
            "species examined" => Section::SpeciesExamined(Skipped::parse(reader, e)?),
            "examined specimens" => Section::SpecimensExamined(Skipped::parse(reader, e)?),
            "literature records" => Section::LiteratureRecords(Skipped::parse(reader, e)?),
            "temporal data" => Section::TemporalData(Skipped::parse(reader, e)?),
            "names" => Section::Names(Skipped::parse(reader, e)?),
            "use" => Section::Uses(Skipped::parse(reader, e)?),
            "specific epithet" => Section::SpecificEpithet(Skipped::parse(reader, e)?),
            "taxon discussion" => Section::Discussion(Skipped::parse(reader, e)?),
            "material" => Section::Material(Skipped::parse(reader, e)?),
            "depth" => Section::Depth(Skipped::parse(reader, e)?),
            "records examined" => Section::RecordsExamined(Skipped::parse(reader, e)?),
            "recognition" => Section::Recognition(Skipped::parse(reader, e)?),
            "included species" => Section::IncludedSpecies(Skipped::parse(reader, e)?),
            "relationships" => Section::Relationships(Skipped::parse(reader, e)?),
            "collecting month and method" => Section::CollectingMethod(Skipped::parse(reader, e)?),
            "original localities" => Section::OriginalLocalities(Skipped::parse(reader, e)?),
            "life history" => Section::LifeHistory(Skipped::parse(reader, e)?),
            "specimens seen" => Section::SpecimensSeen(Skipped::parse(reader, e)?),
            "nomenclatural notes" => Section::Notes(Skipped::parse(reader, e)?),
            "morphological notes" => Section::Notes(Skipped::parse(reader, e)?),
            "bioacoustics" => Section::Bioacoustics(Skipped::parse(reader, e)?),
            "other occurrences" => Section::Occurrences(Skipped::parse(reader, e)?),
            "materials examined" => Section::MaterialsExamined(Skipped::parse(reader, e)?),
            "illustration" => Section::Illustration(Skipped::parse(reader, e)?),
            "comparison." => Section::Comparisons(Skipped::parse(reader, e)?),
            "comparisons" => Section::Comparisons(Skipped::parse(reader, e)?),
            "distribution and bionomics." => Section::Distribution(Skipped::parse(reader, e)?),
            "notes on type material." => Section::Notes(Skipped::parse(reader, e)?),
            "composition" => Section::Composition(Skipped::parse(reader, e)?),
            "taxonomic notes" => Section::Notes(Skipped::parse(reader, e)?),
            "studied type specimens" => Section::SpecimensExamined(Skipped::parse(reader, e)?),
            "additional specimens" => Section::SpecimensExamined(Skipped::parse(reader, e)?),
            "chromosome number" => Section::ChromosomeNumber(Skipped::parse(reader, e)?),
            "basionym" => Section::Basionym(Skipped::parse(reader, e)?),
            "vernacular names" => Section::VernacularNames(Skipped::parse(reader, e)?),
            "lectotype" => Section::Lectotype(Skipped::parse(reader, e)?),
            "referens" => Section::Referens(Skipped::parse(reader, e)?),
            "general features" => Section::Features(Skipped::parse(reader, e)?),
            "other material" => Section::OtherMaterial(Skipped::parse(reader, e)?),
            "diagnostic description" => Section::Diagnostics(Skipped::parse(reader, e)?),
            "literature" => Section::Literature(Skipped::parse(reader, e)?),
            "localities" => Section::Literature(Skipped::parse(reader, e)?),
            "ecological note" => Section::Notes(Skipped::parse(reader, e)?),
            "distribution and habitat" => Section::Distribution(Skipped::parse(reader, e)?),
            "floral associations" => Section::Associations(Skipped::parse(reader, e)?),
            "nesting" => Section::Associations(Skipped::parse(reader, e)?),
            "prey" => Section::Associations(Skipped::parse(reader, e)?),
            "food plants" => Section::FoodPlants(Skipped::parse(reader, e)?),
            "coloration" => Section::Colouration(Skipped::parse(reader, e)?),
            "male" => Section::Male(Skipped::parse(reader, e)?),
            "paratopotype" => Section::Paratopotype(Skipped::parse(reader, e)?),
            "generic placement" => Section::GenericPlacement(Skipped::parse(reader, e)?),
            "description of holotype" => Section::GenericPlacement(Skipped::parse(reader, e)?),
            "coloration of holotype in alcohol" => Section::ColourationInAlcohol(Skipped::parse(reader, e)?),
            "coloration of holotype in life" => Section::ColourationInLife(Skipped::parse(reader, e)?),
            "distribution, natural history, and threats" => Section::NaturalHistory(Skipped::parse(reader, e)?),
            "vernacular_name" => Section::VernacularNames(Skipped::parse(reader, e)?),
            "registration" => Section::Registration(Skipped::parse(reader, e)?),
            "ecology and associated diatom species" => Section::Ecology(Skipped::parse(reader, e)?),
            "notes on natural history" => Section::Notes(Skipped::parse(reader, e)?),
            "type materials" => Section::TypeMaterials(Skipped::parse(reader, e)?),
            "diagnostic information" => Section::Diagnostics(Skipped::parse(reader, e)?),
            "bionomic notes" => Section::Notes(Skipped::parse(reader, e)?),
            "substratum" => Section::Substratum(Skipped::parse(reader, e)?),
            "identification notes" => Section::Notes(Skipped::parse(reader, e)?),
            "standard measurements" => Section::Measurements(Skipped::parse(reader, e)?),
            "types examined" => Section::TypesExamined(Skipped::parse(reader, e)?),
            "anatomy" => Section::Anatomy(Skipped::parse(reader, e)?),
            "similar genera" => Section::Similar(Skipped::parse(reader, e)?),
            "gallery system" => Section::GallerySystem(Skipped::parse(reader, e)?),
            "queen diagnosis" => Section::Diagnosis(Skipped::parse(reader, e)?),
            "caste difference" => Section::CasteDifference(Skipped::parse(reader, e)?),
            "description (male)" => Section::Description(Skipped::parse(reader, e)?),
            "chresonymy" => Section::Chresonymy(Skipped::parse(reader, e)?),
            "coloration of holotype" => Section::Colouration(Skipped::parse(reader, e)?),
            "vocalization" => Section::Vocalization(Skipped::parse(reader, e)?),
            "description of female" => Section::Description(Skipped::parse(reader, e)?),
            "synonyms" => Section::Synonyms(Skipped::parse(reader, e)?),
            "other material examined" => Section::MaterialsExamined(Skipped::parse(reader, e)?),
            "type-species" => Section::TypeSpecies(Skipped::parse(reader, e)?),
            "taxonomy and phylogeny" => Section::Phylogeny(Skipped::parse(reader, e)?),
            "holotype female" => Section::Holotype(Skipped::parse(reader, e)?),
            "host plants" => Section::HostPlants(Skipped::parse(reader, e)?),
            "caves" => Section::Caves(Skipped::parse(reader, e)?),
            "specimens deposited" => Section::SpecimensDeposited(Skipped::parse(reader, e)?),
            "other hosts" => Section::OtherHosts(Skipped::parse(reader, e)?),
            "biological aspects" => Section::Biology(Skipped::parse(reader, e)?),
            "materail" => Section::Material(Skipped::parse(reader, e)?),
            "color of holotype in life" => Section::ColourationInLife(Skipped::parse(reader, e)?),
            "color of holotype in preservative" => Section::ColourationInPreservative(Skipped::parse(reader, e)?),
            "advertisement call" => Section::AdvertisementCall(Skipped::parse(reader, e)?),
            "translation of the latin text" => Section::Translation(Skipped::parse(reader, e)?),
            "taxonomic note" => Section::Notes(Skipped::parse(reader, e)?),
            "malar sulcus" => Section::MalarSulcus(Skipped::parse(reader, e)?),
            "prespecular sulcus" => Section::PrespecularSulcus(Skipped::parse(reader, e)?),
            "transepisternal line" => Section::TransepisternalLine(Skipped::parse(reader, e)?),
            "paracoxal sulcus" => Section::ParacoxalSulcus(Skipped::parse(reader, e)?),
            "metanotal trough" => Section::MetanotalTrough(Skipped::parse(reader, e)?),
            "metascutellum" => Section::Metascutellum(Skipped::parse(reader, e)?),
            "wing venation" => Section::WingVenation(Skipped::parse(reader, e)?),
            "metasomal foveae" => Section::MetasomalFoveae(Skipped::parse(reader, e)?),
            "metasomal segments" => Section::MetasomalSegments(Skipped::parse(reader, e)?),
            "length of metasomal segments" => Section::LengthOfMetasomalSegments(Skipped::parse(reader, e)?),
            "larval morphology" => Section::Morphology(Skipped::parse(reader, e)?),
            "derivation of name" => Section::Names(Skipped::parse(reader, e)?),
            "accompanying taxa" => Section::Taxonomy(Skipped::parse(reader, e)?),
            "original locality" => Section::Locality(Skipped::parse(reader, e)?),
            "included genera and species" => Section::Species(Skipped::parse(reader, e)?),
            "referred specimens" => Section::ReferredSpecimens(Skipped::parse(reader, e)?),
            "locality and age" => Section::Locality(Skipped::parse(reader, e)?),
            "typification" => Section::Typification(Skipped::parse(reader, e)?),
            "ecological notes" => Section::Notes(Skipped::parse(reader, e)?),
            "common name" => Section::VernacularNames(Skipped::parse(reader, e)?),
            "taxonomic remarks" => Section::Notes(Skipped::parse(reader, e)?),
            "morphological comparisons" => Section::Morphology(Skipped::parse(reader, e)?),
            "human uses" => Section::Uses(Skipped::parse(reader, e)?),
            "taxonomic references" => Section::References(Skipped::parse(reader, e)?),
            "species delimitation using dna-barcodes" => Section::SpeciesDelimitation(Skipped::parse(reader, e)?),
            "holotype♀" => Section::Holotype(Skipped::parse(reader, e)?),
            "head" => Section::Head(Skipped::parse(reader, e)?),
            "mesosoma" => Section::Mesosoma(Skipped::parse(reader, e)?),
            "metasoma" => Section::Metasoma(Skipped::parse(reader, e)?),

            "argentinian species checklist" => Section::SpeciesChecklist(Skipped::parse(reader, e)?),

            "key to new zealand kunzea" => Section::Key(Skipped::parse(reader, e)?),
            "key to poa subgen. pseudopoa taxa and other annual species of poa in the coincident geographic region" => {
                Section::Key(Skipped::parse(reader, e)?)
            }
            "revised key to species of eotrechus" => Section::Key(Skipped::parse(reader, e)?),
            "key to species of the genus platycotylus (after merkl 1992 and schawaller 2014)" => {
                Section::Key(Skipped::parse(reader, e)?)
            }
            "key to pipinnipons species" => Section::Key(Skipped::parse(reader, e)?),
            "key to the recent species of errinopora" => Section::Key(Skipped::parse(reader, e)?),
            "key to extant species of planinasus cresson" => Section::Key(Skipped::parse(reader, e)?),

            "local and common names known in cameroon" => Section::VernacularNames(Skipped::parse(reader, e)?),
            "uses in cameroon" => Section::Uses(Skipped::parse(reader, e)?),
            "common names and uses" => Section::VernacularNames(Skipped::parse(reader, e)?),
            "iucn conservation status" => Section::ConservationStatus(Skipped::parse(reader, e)?),
            "iucn red list status" => Section::ConservationStatus(Skipped::parse(reader, e)?),
            "national red list status" => Section::ConservationStatus(Skipped::parse(reader, e)?),
            "published (original) locality" => Section::Locality(Skipped::parse(reader, e)?),
            "georgian name" => Section::Names(Skipped::parse(reader, e)?),
            "chinese name" => Section::Names(Skipped::parse(reader, e)?),
            "present name" => Section::Names(Skipped::parse(reader, e)?),

            "canadian records" => Section::Records(Skipped::parse(reader, e)?),
            "additional canadian records" => Section::Records(Skipped::parse(reader, e)?),
            "distribution in canada and alaska" => Section::Distribution(Skipped::parse(reader, e)?),
            "distribution in argentina" => Section::Distribution(Skipped::parse(reader, e)?),
            "distribution in turkey" => Section::Distribution(Skipped::parse(reader, e)?),
            "iran localities" => Section::Localities(Skipped::parse(reader, e)?),
            "s. parvulus worker diagnosis" => Section::Diagnosis(Skipped::parse(reader, e)?),
            "s. parvulus male" => Section::Male(Skipped::parse(reader, e)?),
            "s. parvulus geographic range" => Section::Range(Skipped::parse(reader, e)?),
            "s. parvulus larva" => Section::LarvaPupa(Skipped::parse(reader, e)?),
            "s. parvulus notes" => Section::Notes(Skipped::parse(reader, e)?),

            "species of neocerapachys" => Section::Species(Skipped::parse(reader, e)?),
            "eggs/spiderlings" => Section::Eggs(Skipped::parse(reader, e)?),
            "sampling/reporting sites" => Section::SamplingSites(Skipped::parse(reader, e)?),
            "external morphology of the genital organs" => Section::Morphology(Skipped::parse(reader, e)?),
            "internal morphology of the genital organs" => Section::Morphology(Skipped::parse(reader, e)?),
            "abdominal pits and male genital morphology" => Section::Morphology(Skipped::parse(reader, e)?),

            "" => Section::Unknown(Skipped::parse(reader, e)?),

            _subsection_type => Section::Skipped(Skipped::parse(reader, e)?),
            // subsection_type => panic!("Unknown subsection type: {subsection_type}"),
        };

        Ok(SubSection { section })
    }
}
