name: Compile the oplogger binary

on:
  push:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install rust-cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo build --release

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: oplogger
          path: target/release/oplogger

      - name: Artifact details
        run:  |
          echo 'id: ${{ steps.artifact-upload-step.outputs.artifact-id }}'
          echo 'url: ${{ steps.artifact-upload-step.outputs.artifact-url }}'
