name: Mirror repository to codeberg

on: [push]

jobs:
  sync-codeberg-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'ssh://codeberg.org/ARGA/arga-oplogger.git'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_MIRROR_SSH_PRIVATE_KEY }}
          GIT_SSH_KNOWN_HOSTS: ${{ secrets.GIT_MIRROR_SSH_KNOWN_HOSTS }}
          GIT_SSH_NO_VERIFY_HOST: "true"
